local detect = require("nvim-stm32.detect")

local function fixture(rel)
  local here =
    vim.fn.fnamemodify(vim.fn.resolve(debug.getinfo(1, "S").source:sub(2)), ":p:h")
  return here .. "/fixtures/" .. rel
end

describe("nvim-stm32.detect file readers", function()
  it("reads Mcu.Name and board out of a real .ioc", function()
    local mcu, board = detect.read_ioc(fixture("nucleo_cmake/dt.ioc"))
    assert.equals("STM32F429ZITx", mcu)
    assert.equals("NUCLEO-F429ZI", board)
  end)

  it("returns nil for a file that is not an .ioc", function()
    assert.is_nil(detect.read_ioc(fixture("nucleo_cmake/CMakeLists.txt")))
  end)

  it("reads the part number out of a startup file name", function()
    assert.equals("STM32F429XX", detect.mcu_from_startup("startup_stm32f429xx.s"))
    assert.is_nil(detect.mcu_from_startup("main.c"))
  end)

  it("reads both linker script spellings", function()
    assert.equals("STM32F429XX", detect.mcu_from_linker("STM32F429xx_FLASH.ld"))
    assert.equals("STM32F429ZITX", detect.mcu_from_linker("STM32F429ZITX_FLASH.ld"))
    assert.equals("STM32F401RETX", detect.mcu_from_linker("STM32F401RETx_RAM.ld"))
  end)

  it("rejects a linker script whose name is not a part number", function()
    assert.is_nil(detect.mcu_from_linker("linker_script.ld"))
    assert.is_nil(detect.mcu_from_linker("STM32F429xx_FLASH.txt"))
  end)

  it("finds the device macro in CubeMX's generated CMakeLists", function()
    local mcu, core, fpu = detect.scan_cmake(fixture("cmake_only"))
    assert.equals("STM32F429xx", mcu)
    assert.equals("cortex-m4", core)
    assert.equals("fpv4-sp-d16", fpu)
  end)
end)

describe("nvim-stm32.detect.mcu", function()
  it("takes the .ioc and calls it exact when every signal agrees", function()
    local res = detect.mcu(fixture("nucleo_cmake"))
    assert.equals("STM32F429ZITx", res.mcu)
    assert.equals("NUCLEO-F429ZI", res.board)
    assert.equals("exact", res.confidence)
    assert.equals(4, #res.signals)
    assert.equals(4, res.agreement)
    assert.equals("ioc", res.signals[1].source)
  end)

  it("resolves from the linker script alone, as inferred", function()
    local res = detect.mcu(fixture("linker_only"))
    assert.equals("STM32F429ZITX", res.mcu)
    assert.equals("inferred", res.confidence)
    assert.equals(1, res.agreement)
  end)

  it("resolves from the startup file alone, as inferred", function()
    local res = detect.mcu(fixture("startup_only"))
    assert.equals("STM32F429XX", res.mcu)
    assert.equals("inferred", res.confidence)
    assert.equals("startup", res.signals[1].source)
  end)

  it("resolves from the CMake files alone, and keeps the measured flags", function()
    local res = detect.mcu(fixture("cmake_only"))
    assert.equals("STM32F429xx", res.mcu)
    assert.equals("inferred", res.confidence)
    assert.equals("cortex-m4", res.core)
    assert.equals("fpv4-sp-d16", res.fpu)
  end)

  it("lets the .ioc win over a linker script that disagrees", function()
    local res = detect.mcu(fixture("conflict"))
    assert.equals("STM32F429ZITx", res.mcu)
    assert.equals("exact", res.confidence)
    assert.equals(2, #res.signals)
    assert.equals(1, res.agreement)
  end)

  it("reports unknown when no signal fires", function()
    local res = detect.mcu(fixture("makefile_only"))
    assert.equals("unknown", res.confidence)
    assert.is_nil(res.mcu)
    assert.equals(0, res.agreement)
  end)
end)

describe("nvim-stm32.detect.target", function()
  it("assembles the whole Target for the board on the desk", function()
    local t = detect.target(fixture("nucleo_cmake/Core/Src"))
    assert.equals(fixture("nucleo_cmake"), t.root)
    assert.equals("cmake_presets", t.build_backend)
    assert.equals("STM32F429ZITx", t.mcu)
    assert.equals("STM32F4", t.family)
    assert.equals("cortex-m4", t.core)
    assert.equals("fpv4-sp-d16", t.fpu)
    assert.equals(2048, t.flash_kb)
    assert.equals(256, t.ram_kb)
    assert.equals("NUCLEO-F429ZI", t.board)
    assert.equals("target/stm32f4x.cfg", t.openocd_cfg)
    assert.equals("exact", t.confidence)
    assert.is_nil(t.elf)
  end)

  it("still returns a buildable Target when the chip is unknown", function()
    local t = detect.target(fixture("makefile_only"))
    assert.equals("unknown", t.confidence)
    assert.equals("make", t.build_backend)
    assert.is_nil(t.mcu)
    assert.is_nil(t.family)
  end)

  it("returns an error naming the directory when there is no project", function()
    local tmp = vim.fn.tempname()
    vim.fn.mkdir(tmp .. "/.git", "p")
    vim.fn.mkdir(tmp .. "/src", "p")
    local t, err = detect.target(tmp .. "/src")
    assert.is_nil(t)
    assert.is_truthy(err:find(tmp, 1, true))
    vim.fn.delete(tmp, "rf")
  end)
end)
