describe("test harness", function()
  it("loads the plugin module from the runtimepath", function()
    local ok, mod = pcall(require, "nvim-stm32")
    assert.is_true(ok)
    assert.equals("table", type(mod))
  end)

  it("runs on a Neovim the plugin supports", function()
    assert.equals(1, vim.fn.has("nvim-0.11"))
  end)
end)
